USE GamePickerDB;

INSERT INTO Game (GameID, GameName, Developer, ReleaseDate, GenreID, Description)
VALUES 
(1000, 'Cyberpunk 2077', 'Cd Projekt Red', '2020-12-10', 2, 'Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a dangerous megalopolis obsessed with power, glamor, and ceaseless body modification.'),
(1001, 'Bioshock Infinite', 'Irrational Games', '2013-03-26', 5, 'Indebted to the wrong people, with his life on the line, veteran of the U.S. Cavalry and now hired gun, Booker DeWitt has only one opportunity to wipe his slate clean. He must rescue Elizabeth, a mysterious girl imprisoned since childhood and locked up in the flying city of Columbia.'),
(1002, 'Dark Souls 3', 'From Software', '2023-10-01', 6, 'Dark Souls continues to push the boundaries with the latest, ambitious chapter in the critically-acclaimed and genre-defining series. Prepare yourself and Embrace The Darkness!'),
(1003, 'Elden Ring', 'From Software', '2023-10-02', 2, 'Elden Ring is a 2022 action role-playing game developed by FromSoftware. It was directed by Hidetaka Miyazaki with worldbuilding provided by fantasy writer George R. R. Martin.'),
(1004, 'Baldur''s Gate 3', 'Larian Studios', '2023-10-03', 2, 'Baldur''s Gate 3 is a role-playing video game developed and published by Larian Studios. It is the third main game in the Baldur''s Gate series, based on the tabletop role-playing system of Dungeons & Dragons'),
(1005, 'Battlefield 2042', 'Dice', '2021-11-19', 9, 'Battlefield™ 2042 is a first-person shooter that marks the return to the iconic all-out warfare of the franchise.'),
(1006, 'Hollow Knight', 'Team Cherry', '2017-02-24', 5, 'Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style.'),
(1007, 'Dying Light: Definitive Edition', 'Techland', '2021-05-27', 3, 'First-person action survival game set in a post-apocalyptic open world overrun by flesh-hungry zombies. Roam a city devastated by a mysterious virus epidemic. Scavenge for supplies, craft weapons, and face hordes of the infected.'),
(1008, 'The Elder Scrolls V: Skyrim Special Edition', 'Bethesda Game Studios', '2016-10-28', 3, 'Winner of more than 200 Game of the Year Awards, Skyrim Special Edition brings the epic fantasy to life in stunning detail. The Special Edition includes the critically acclaimed game and add-ons with all-new features like remastered art and effects, volumetric god rays, dynamic depth of field, screen-space reflections, and more.'),
(1009, 'Borderlands 3', 'Gearbox Software', '2019-09-13', 9, 'The original shooter-looter returns, packing bazillions of guns and a mayhem-fueled adventure! Blast through new worlds and enemies as one of four new Vault Hunters.'),
(1010, 'Hades', 'Supergiant games', '2018-12-06', 10, 'Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion, Transistor, and Pyre.');
